### ISSUE TITLE
Suggestion: Discord links

### ISSUE THREAD

**Issue by ChloeDawn** [TerraformersMC/ModMenu#23]
Support for linking a discord server for a mod, or a discord account for an author.

`"discord": "Username#0000"`
`"discord": "ServerId"`

**Comment by Prospector** [comment]
Where do you think a button for that should go? You also requested source links, where should that go?

**Comment by asiekierka** [comment]
I'd say Discord URLs should take the form of an invite for "discord" and perhaps "discord-id" for user accounts, myself.

**Comment by Prospector** [comment]
loader schema v2?

**Comment by InsomniaKitten** [comment]
Doesn't need a new schema, it would be new data not changed data

**Comment by InsomniaKitten** [comment]
And yeah, an invite would be more appropriate for servers, didn't think about that too much. I'm moreso interested in username metadata for contact info

**Comment by Prospector** [comment]
Right now Mod Menu doesn't display any info for people though currently. Not sure how I would display it since it's mainly meant to show mods not authors

**Comment by sargunv** [comment]
Rather than specifically adding support for Discord links, why not just add generalized support for a custom list of links that gets appended to the description as a list of clickable blue links? No extra UI real-estate usage (it's just after the description in the scrollable pane), no locking people into discord (they may have some other form of community), and not much additional UI clutter (blue links "feel" less like part of the UI and more like content, unlike buttons).

**Comment by JustJinxed** [comment]
I'm not sure it needs a userid field per say, as some mods are maintained by a collection. but whateves.. The link to the discord server and/or website would be nice. Even if you have to pop a second window with a close button, and just call it, "more info"
