### ISSUE TITLE
Suggestion: Compact mod list?

### ISSUE THREAD

**Issue by ghost** [TerraformersMC/ModMenu#56]
What do you think about compact mod list? (Ignore the other tweaks and changes)

![](https://i.imgur.com/5hvlMeY.png)

**Comment by Prospector** [comment]
Upon further thought, I don't think a compact list like this would currently fit Mod Menu. The problem with removing icons as you've done (or making them smaller) is it would require a bit of rethinking about how the expanding/collapsing child and parent mods would work. Gonna leave it open though, because it's something I'm still considering.

**Comment by modmuss50** [comment]
Yeah, not sure how child mods would work with this, could possibly add a little button right aligned with the title?
